<?php
/**
 * Implements hook_views_api().
 */
function views_cache_tags_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'views_cache_tags') . '/views',
  );
}

/**
 * The CID for specified tids cache tag.
 */
function _views_cache_tags_tid_cache_tag_cid($tid) {
  return 'term_cache_tag_' . intval($tid);
}

/**
 * Get the cache tag for specified tid.
 */
function views_cache_tags_tid_cache_tag($tid) {
  $cache = cache_get(_views_cache_tags_tid_cache_tag_cid($tid));
  if (isset($cache->data)) {
    return $cache->data;
  }

  return views_cache_tags_tid_cache_tag_reset($tid);
}

/**
 * Set cache tag for specified tid.
 */
function views_cache_tags_tid_cache_tag_reset($tid) {
  $cache_tag = 'term_cache_tag_' . intval($tid) . '_' . time();
  cache_set(_views_cache_tags_tid_cache_tag_cid($tid), $cache_tag);
  return $cache_tag;
}

/**
 * Implements hook_node_insert().
 *
 * @param $node
 */
function views_cache_tags_node_insert($node) {
  views_cache_tags_invalidate_cache($node);
}

/**
 * Implements hook_node_delete().
 *
 * @param $node
 */
function views_cache_tags_node_delete($node) {
  views_cache_tags_invalidate_cache($node);
}

/**
 * Implements hook_node_update().
 *
 * @param $node
 */
function views_cache_tags_node_update($node) {
  // Invalidate for the updated node.
  views_cache_tags_invalidate_cache($node);
  // Also invalidate the cache for the old version of the node.
  if (isset($node->original)) {
    views_cache_tags_invalidate_cache($node->original);
  }
}

/**
 * Invalidate caches.
 *
 * @param $node
 */
function views_cache_tags_invalidate_cache($node) {
  // Loop the term reference fields and reset the cache tags.
  $term_fields = _views_cache_tags_get_taxonomy_fields($node->type);
  foreach ($term_fields as $field_name => $field_info) {
    if (isset($node->{$field_name})) {
      // Reset the term cache tag.
      if (isset($node->{$field_name}[LANGUAGE_NONE][0])) {
        foreach ($node->{$field_name}[LANGUAGE_NONE] as $key => $value) {
          views_cache_tags_tid_cache_tag_reset($value['tid']);
          // Also invalidate parent term tags.
          if ($parent_terms = taxonomy_get_parents_all($value['tid'])) {
            foreach ($parent_terms as $parent_term) {
              views_cache_tags_tid_cache_tag_reset($parent_term->tid);
            }
          }
        }
      }
    }
  }
}

/**
 * Helper to get list of term reference fields.
 *
 * @param $node_type
 * The node type.
 * @return
 * List of term reference field names.
 */
function _views_cache_tags_get_taxonomy_fields($node_type) {
  $taxonomy_fields = &drupal_static(__FUNCTION__ . $node_type, array());
  if (!empty($taxonomy_fields[$node_type])) {
   return $taxonomy_fields[$node_type];
  }
  if ($entity_info = field_info_instances('node', $node_type)) {
    foreach ($entity_info as $field) {
      $field_name = $field['field_name'];
      $field_info = field_info_field($field_name);
      if ($field_info['type'] == 'taxonomy_term_reference') {
        $taxonomy_fields[$node_type][$field_name] = $field_info;
      }
    }
  }
  return $taxonomy_fields[$node_type];
}
